#!/bin/sh

            grep -q "# SAMBA NetBIOS services" /etc/inetd.conf || echo "# SAMBA NetBIOS services (for PC file and print sharing)
netbios-ssn stream tcp nowait root /usr/sbin/smbd smbd
" >> /etc/inetd.conf

            grep -q "microsoft-ds stream tcp nowait root /usr/sbin/smbd smbd" /etc/inetd.conf || echo "microsoft-ds stream tcp nowait root /usr/sbin/smbd smbd" >> /etc/inetd.conf
